### ISSUE TITLE
[ENHANCEMENT] Implement widgets charts to data entity

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#149]
**Describe the solution you'd like**
Allow users to render data on a chart and provide embed code to allow them embed the chart in their own environment.

Also allow users to embed data results in a datatable in their own environment by providing embed code.

Re-factor data entity code to be modular for data, charts and maps

**Comment by damienderoistecso** [comment]
@liamie @JohnPCarroll ready for test

**Comment by liamie** [comment]
Pie charts popup info for section seems to be based on left to right movement rather than section selected/highlighted or clicked.
image

**Comment by damienderoistecso** [comment]
Updated config to remove tooltips.intersect = false

@liamie ready for re-test

**Comment by liamie** [comment]
Pie and Doughnut section selection seems to be correct now

**Comment by damienderoistecso** [comment]
> filter option allows multiple different X-Axis to be chosen for different series combinations which breaks line charts, and similar for other multi series charts.
> after first series created
> you can return to xaxis and use filter to activate a different classification for x-axis
> ![image](https://user-images.githubusercontent.com/55874862/88052669-7cd03c80-cb52-11ea-9195-640d751d79cf.png)
> 
> series 1
> ![image](https://user-images.githubusercontent.com/55874862/88052746-a5583680-cb52-11ea-9391-a9e9410c3d5e.png)
> 
> series 2 (now has option of census year which was x axis previous)
> ![image](https://user-images.githubusercontent.com/55874862/88052854-ce78c700-cb52-11ea-98e2-d13e38b83dac.png)
> 
> and so get different series which breaks the chart
> ![image](https://user-images.githubusercontent.com/55874862/88051772-11399f80-cb51-11ea-8fd0-958ffc54ac71.png)

Fixed, disabled filter input for non selected xAxis dimensions
@liamie ready for re-test

**Comment by liamie** [comment]
@damienderoistecso Filter on other options for X-Axis locking correctly now

**Comment by JohnPCarroll** [comment]
Issue with Column type table
Table VSA50. Selected Years 2016 to 2019. 
Selected Jack and Sean as the 2 series 
![image](https://user-images.githubusercontent.com/44975474/88065620-be69e300-cb64-11ea-9a00-f7b77ad0981e.png)

Chart with 2 series 
![image](https://user-images.githubusercontent.com/44975474/88065760-ebb69100-cb64-11ea-9708-246c62e05ab3.png)

Removed Sean and Jacks last value is not seen
![image](https://user-images.githubusercontent.com/44975474/88065968-25879780-cb65-11ea-902c-a09c5e32a540.png)

**Comment by liamie** [comment]
In charts with the dual axis option the drop down for the Y-Axis has two options for left and two for right. Should only be one of each.

![image](https://user-images.githubusercontent.com/55874862/88070046-22db7100-cb6a-11ea-8299-8e77ea10c689.png)

**Comment by damienderoistecso** [comment]
> @damienderoistecso
> In charts with the dual axis option the drop down for the Y-Axis has two options for left and two for right. Should only be one of each.
> _update_ the number of Left and Rights increases by one every time the Dual Axis is toggled
> ![image](https://user-images.githubusercontent.com/55874862/88071305-8dd97780-cb6b-11ea-8e6d-717a45664acd.png)
> ![image](https://user-images.githubusercontent.com/55874862/88071651-02141b00-cb6c-11ea-9d0d-4cad1bbe9435.png)

Should be fixed now. 
@liamie ready for re-test

**Comment by damienderoistecso** [comment]
> Issue with Column type table ( Auto Scale is TRUE
> Table VSA50. Selected Years 2016 to 2019.
> Selected Jack and Sean as the 2 series
> ![image](https://user-images.githubusercontent.com/44975474/88065620-be69e300-cb64-11ea-9a00-f7b77ad0981e.png)
> 
> Chart with 2 series
> ![image](https://user-images.githubusercontent.com/44975474/88065760-ebb69100-cb64-11ea-9708-246c62e05ab3.png)
> 
> Removed Sean and Jacks last value is not seen
> ![image](https://user-images.githubusercontent.com/44975474/88065968-25879780-cb65-11ea-902c-a09c5e32a540.png)
> 
> When I remove Jack and leave Sean in everything is correct
> ![image](https://user-images.githubusercontent.com/44975474/88067353-c9257780-cb66-11ea-8c7a-edf8ee053769.png)

This is because auto-scale is set to true. If you set auto-scale to false, it works better when removing one series

**Comment by liamie** [comment]
@damienderoistecso Dual-Axis toggle incrementing instance of Left/Right seems corrected now

**Comment by JohnPCarroll** [comment]
Table VSA50: Omer has no value for 2019 by the letters NaN appear in 2019
Issue with no values in item
![image](https://user-images.githubusercontent.com/44975474/88160402-7d2a0f80-cc06-11ea-8298-bcc11823527a.png)

**Comment by JohnPCarroll** [comment]
Legend issue on column chart 
1. You change the Legend to None and no chart is available. This is correct.
2. You switch the Legend to another option and the chart is still not available. This is incorrect

**Comment by JohnPCarroll** [comment]
Table VSA50 : In Bar Chart years are displayed incorrectly

![image](https://user-images.githubusercontent.com/44975474/88163643-e744b380-cc0a-11ea-8e4e-c9944b921dd3.png)

**Comment by damienderoistecso** [comment]
> Table VSA50: Omer has no value for 2019 by the letters NaN appear in 2019
> Issue with no values in item
> ![image](https://user-images.githubusercontent.com/44975474/88160402-7d2a0f80-cc06-11ea-8298-bcc11823527a.png)

@JohnPCarroll should be fixed now. Can you re-test

**Comment by JohnPCarroll** [comment]
Issue with NaN appearing when no values exist is resolved. Double dots appear

**Comment by damienderoistecso** [comment]
> Table VSA50 : In Bar Chart years are displayed incorrectly
> 
> ![image](https://user-images.githubusercontent.com/44975474/88163643-e744b380-cc0a-11ea-8e4e-c9944b921dd3.png)

Should be fixed now
@JohnPCarroll can you re-test

**Comment by damienderoistecso** [comment]
> Legend issue on column chart
> 
> 1. You change the Legend to None and no chart is available. This is correct.
> 2. You switch the Legend to another option and the chart is still not available. This is incorrect

Should be fixed. Every time you change the legend position, you need to click the 'View' button again
@JohnPCarroll ready for test

**Comment by JohnPCarroll** [comment]
Legend Issue Resolved. You can remove the Legend and Click on 'View' Button you see the rest of the table. Once another option for the legend is selected and you Click 'View' all is correct.

The years are still incorrectly displayed on the bar chart

**Comment by damienderoistecso** [comment]
> Legend Issue Resolved. You can remove the Legend and Click on 'View' Button you see the rest of the table. Once another option for the legend is selected and you Click 'View' all is correct.
> 
> The years are still incorrectly displayed on the bar chart

Years should be fixed now
@JohnPCarroll ready for re-test

**Comment by JohnPCarroll** [comment]
Years now correct.

**Comment by JohnPCarroll** [comment]
When you download a chart the Copyright and Source is lost in the .png file created

**Comment by damienderoistecso** [comment]
> When you download a chart the Copyright and Source is lost in the .png file created

The copyright and source are outside of the SVG canvas, so they cannot be included in the .png download

**Comment by JohnPCarroll** [comment]
Table VSA50 : No values are appearing in the Doughnut Chart
![image](https://user-images.githubusercontent.com/44975474/88266465-2df7e380-ccc7-11ea-946d-67e0fced1d29.png)

**Comment by damienderoistecso** [comment]
> Table VSA50 : No values are appearing in the Doughnut Chart or Pie Charts ( image not included)
> ![image](https://user-images.githubusercontent.com/44975474/88266465-2df7e380-ccc7-11ea-946d-67e0fced1d29.png)

Should be fixed now

@JohnPCarroll can you re-test. Can you also DOUBLE CHECK the values are correct! I had to change how I read the values.

**Comment by JohnPCarroll** [comment]
Test passed. Data Values are correct

**Comment by lorenzobruni** [comment]
Hi @JohnPCarroll  / @liamie 
I see this one is still assigned to you both with no `TESTED` label attached, but last comment was test passed.

Can you please confirm if all is good and if so reassign to me and attach the `TESTED` label?

Thanks
