### ISSUE TITLE
[BUG] Inconsistent approach to Historical Releases

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#237]
On the release page public comments section of an historical page 

![image](https://user-images.githubusercontent.com/55874862/95198425-24185380-07d3-11eb-9454-820e954a22a4.png)
The update button is greyed out but the delete button can still be used to delete the comment

Neither option should be available on an historical release

On the server the api currently allows for update and delete of public comments on historical releases 
This should not be allowed on an historical release

**Comment by damienderoistecso** [comment]
Client fixed

**Comment by neilfromcork** [comment]
Looks ok to me

**Comment by liamie** [comment]
Fixed now to not update, create or delete on historical releases.
Assigned to @JohnPCarroll to test for any impact on public comments elsewhere

**Comment by JohnPCarroll** [comment]
Update and delete are unavailable for historical release.
Issue with live Release. If you decide to update a public comment and then select the cancel button. The new comment remains if you go back in. The old one should appear.
![image](https://user-images.githubusercontent.com/44975474/95338244-a6277b80-08aa-11eb-9502-346e1bb2547b.png)

**Comment by damienderoistecso** [comment]
> Update and delete are unavailable for historical release.
> Issue with live Release. If you decide to update a public comment and then select the cancel button. The new comment remains if you go back in. The old one should appear.
> ![image](https://user-images.githubusercontent.com/44975474/95338244-a6277b80-08aa-11eb-9502-346e1bb2547b.png)

Fixed in dev

@JohnPCarroll ready for test

**Comment by JohnPCarroll** [comment]
Issue with comment amended in update modal not resolved. The same happens if you Add a public comment. The comment entered is not removed if you select the add or update buttons

**Comment by damienderoistecso** [comment]
> Issue with comment amended in update modal not resolved. The same happens if you Add a public comment. The comment entered is not removed if you select the add or update buttons

@JohnPCarroll Fixed now in dev ready for test

**Comment by JohnPCarroll** [comment]
Issue with comments not resetting to initial value in modal add and update comments resolved.
Test past in relation to historical buttons not active
