### ISSUE TITLE
[BUG] ReadCopyright is not open to non-px users

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#292]
ReadCopyright requires PxStat privileges. It should be open. Also, check documentation for wrong entries regarding privilege on Reads.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by lorenzobruni** [comment]
@neilfromcork  
The issue persists... has it been published? thanks
![image](https://user-images.githubusercontent.com/53212047/99716554-28a57c80-2aa0-11eb-82df-84e73cb0383c.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by lorenzobruni** [comment]
Test passed
