### ISSUE TITLE
[ENHANCEMENT] Allow users to save favorite tables against their profile

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#494]
All all types of users (AD, local, subscribers) to save tables as favorites so they can quickly access those tables from the homepage once they are logged in.

The users will also have the option to remove tables from favorites later

**Comment by liamie** [comment]
**Describe the bug**
Normally when you go to a page that you have already favourited the favourite button is set to remove rather than add however if you use the share link or direct link the button is back in the add favourite state however if  you go through the steps the already favourite error appears.
Using share table link/direct link to access table pages affects state of the add to favourites button. 
**To Reproduce**
Steps to reproduce the behavior:
Use share or direct link to already favourited page
![image](https://user-images.githubusercontent.com/55874862/153587746-bc7ef581-79b4-4851-8399-78a77cb3b76b.png)

2.  Favourite button is now back to this 
![image](https://user-images.githubusercontent.com/55874862/153587937-4f157e33-9221-4c58-876d-957c3883245f.png)
rather than expected 
![image](https://user-images.githubusercontent.com/55874862/153588087-a0dc1615-e448-48f5-89d0-a9b63682dbbd.png)

3. Also incorrectly allows you to try add the already favourited table via the button, rather than remove however the error is correct at this point.
![image](https://user-images.githubusercontent.com/55874862/153588719-51dbe795-f083-45d5-8908-597594381214.png)


**Expected behavior**
Favourite button to reflect already favourite no matter how table page is accessed once user is the same

**Comment by damienderoistecso** [comment]
Fixed in test @liamie

**Comment by liamie** [comment]
> 

Yes this takes a second to load but does self correct automatically now

**Comment by liamie** [comment]
Sometimes when logging in the favourite tables panel does not render. and can be made rerender by adding a new table to the list.
this does not always occur and can also generate an error
![image](https://user-images.githubusercontent.com/55874862/160808443-5f183052-dd17-4532-aa07-dd9c995254a8.png)
going to product can also make this section disappear similar to described above maybe reoccurring now

**Comment by damienderoistecso** [comment]
> Sometimes when logging in the favourite tables panel does not render. and can be made rerender by adding a new table to the list. this does not always occur and can also generate an error ![image](https://user-images.githubusercontent.com/55874862/160808443-5f183052-dd17-4532-aa07-dd9c995254a8.png) going to product/sharelink can also make this section disappear similar to add/remove button error described previous

Fixed in test @liamie

**Comment by liamie** [comment]
@damienderoistecso language text can push favorites out of boundary still occurring
