### ISSUE TITLE
[BUG] when users log in through 2FA, they are anonymous in tracing

### ISSUE THREAD

**Issue by 1556953** [CSOIreland/PxStat#504]
Non active directory users are appearing as anonymous in both application tracing and in the system generated workflow emails
![image](https://user-images.githubusercontent.com/60383775/151176016-f7669e42-9765-4958-93e5-fd6e22327bb7.png)

![image](https://user-images.githubusercontent.com/60383775/151176169-2d189232-5870-46b2-9f70-715a8afcbbed.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Local User, signed in with 2FA still appears as anonymous in trace

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
2fa users are  displaying in trace now.
Note: anonymous seems to be appearing on some occasions for some actions.

**Comment by liamie** [comment]
Complete as per specified
