### ISSUE TITLE
[ENHANCEMENT] Make Firebase options configurable 

### ISSUE THREAD

**Issue by CSOIrelandTechnology** [CSOIreland/PxStat#542]
Make firebase integration more configurable in terms of using it or selecting the 3rd party authentication types

**Comment by damienderoistecso** [comment]
Fixed in dev

No you can opt out of all subscriber functionality as well as picking only the sign in providers you want

@liamie We need to test it with 2fa enabled and also with 2fa disabled as the login button behaves differently depending on this scenario

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/163355582-9cb3c948-aa70-4843-becb-1e9c2eb416c2.png)

Stay Logged In Button Remains even when firebase options are not enabled.

**Comment by damienderoistecso** [comment]
> ![image](https://user-images.githubusercontent.com/55874862/163355582-9cb3c948-aa70-4843-becb-1e9c2eb416c2.png)
> 
> Stay Logged In Tick Box Remains even when affected firebase options are not enabled.

Fixed in dev @liamie ready for testing

**Comment by liamie** [comment]
Stay logged in gone now if no standard subscriber login option is available.
However still appears in Email option only displayed even though this has its own stay logged in after clicking button
![image](https://user-images.githubusercontent.com/55874862/166425989-e96d8dcd-de2f-4a7b-b499-034c1c0a36da.png)

**Comment by liamie** [comment]
The extra stay logged in gone now
