### ISSUE TITLE
[BUG]  Tables associated with Maps not appearing in dev

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#565]
**Describe the bug**

**To Reproduce**
in dev
1. Go to Build
2. Click on Maps

on live 
1. System
2. Maps

**Expected behavior**
Table count to appear on screen on the Tables column and the list of tables in modal to appear when the number is clicked as per below

On Dev
![image](https://user-images.githubusercontent.com/55874862/167829044-ef49b9fc-f1bc-471d-96b3-4e183d329aab.png)

![image](https://user-images.githubusercontent.com/55874862/167827253-80e6dee8-a724-4218-ab0a-7d2420f907c3.png)

On Live

![image](https://user-images.githubusercontent.com/55874862/167827758-683eee8d-4e5c-44c8-9c67-9236770a2902.png)

![image](https://user-images.githubusercontent.com/55874862/167828796-f2ef862e-4c17-43f6-92c9-7556fc35644b.png)

**Comment by liamie** [comment]
#541 listed associated API I think

**Comment by liamie** [comment]
Map tab not appearing on tables that should have maps either

dev
![image](https://user-images.githubusercontent.com/55874862/167832848-b0d6bbb2-87fd-4f58-a6db-fb3714fcde74.png)

live
![image](https://user-images.githubusercontent.com/55874862/167833051-9174ab4e-c46f-4a69-873e-a1c15321fef0.png)

Is it that the database transfer keeps the old links but now the new front end is looking at a different/for a different source as not imported through the front end?

**Comment by neilfromcork** [comment]
Fixed in DEV, ready for test

**Comment by liamie** [comment]
Map Tab now appearing on files but the build maps still showing 0 for all except one or two newly created. And no tables listed on modal that appears on clicking.

**Comment by damiancosmoschapman** [comment]
I think the build maps showing 0 for all but the newly created makes sense as the build maps urls point to the live environment which is not visible in dev.

**Comment by liamie** [comment]
map tabs appear now and the table listing issue is associated with the links pointing in different locations as explained above.
