### ISSUE TITLE
[BUG] csv downloads are incorrect in new dev

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#566]
**Describe the bug**
For single Statistic Table - G0316
The csv created is the same for codes on or off which is incorrect. 
The column heading do not match with the data rows. There is a blank row at the end. 
The output does not match the live environment

**To Reproduce**
Download the csv files with codes on and off. 

**Expected behavior**
If the codes are off they should not be included and if on they should be.

**Screenshots**
Single statistic codes off ( this is incorrect ) - Taken from DEV
![image](https://user-images.githubusercontent.com/44975474/167867368-bffb6fe9-8d97-4ea6-94aa-0485d88e9f7d.png)

Single statistic codes on ( this is incorrect ) - Taken from DEV
![image](https://user-images.githubusercontent.com/44975474/167867640-0d436979-63bc-43a6-8736-58893fda3452.png)

live environment
Codes off
![image](https://user-images.githubusercontent.com/44975474/167868264-ea9a7dcb-60df-4135-bd60-aff5ebc8ccd9.png)

Codes on
![image](https://user-images.githubusercontent.com/44975474/167868512-6c04d2a7-ad44-47d9-b134-306c1b7d2764.png)

**Comment by liamie** [comment]
UNIT seems to be dropped on CSV downloads of pivoted results and a trailing comma can remain on lines giving a blank column on lefthandside

**Comment by neilfromcork** [comment]
Can't replicate. Looks ok for G0316

**Comment by JohnPCarroll** [comment]
If you pivot a classification and then download as follows the issue happens

![image](https://user-images.githubusercontent.com/44975474/168586760-ca71ad58-5e84-42db-86be-9e000dca84c1.png)

**Comment by neilfromcork** [comment]
Fixed in DEV, ready for test

**Comment by JohnPCarroll** [comment]
Pivot applied and then downloaded as above. This is not a full download
Table details incorrect and heading contains codes instead of names. All values bar first line appear to be incorrect

Dev Environment
![image](https://user-images.githubusercontent.com/44975474/168759525-8e41820d-90bc-44eb-9320-06e1a35c5ed4.png)

live Environment

![image](https://user-images.githubusercontent.com/44975474/168759983-b1aa3e24-eb78-440f-ac4d-6f7eb2a3cb30.png)

**Comment by neilfromcork** [comment]
Remove trailing comma
Ensure codes/values same as production

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. Please test with Excel as well.

**Comment by liamie** [comment]
Still difference between csv on live and dev

LMPMQ01 Dev
![image](https://user-images.githubusercontent.com/55874862/169270173-dc879eac-2e07-4a63-b5b4-93025007b336.png)

PMQ01 Live
![image](https://user-images.githubusercontent.com/55874862/169269695-73d5bd41-d6a1-496c-90f5-74d7d63695b6.png)

**Comment by liamie** [comment]
problem still present 
compare CSV outputs for dev LMHFC2013 
live HFC2013  additional columns in dev as with PMQ01 above

**Comment by JohnPCarroll** [comment]
Test Passed

**Comment by liamie** [comment]
code true/false seems to be correctly reflected in dev now
