### ISSUE TITLE
Build Update not adding default values as default.

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#614]
Build Update not adding default values as default.

If a new time period is added to Build Update of a px file the values are defaulted to null/blank "" rather than double dots ".."
So the file won't create as default.
Live
file creates as .. is in for defaults
Dev
![image](https://user-images.githubusercontent.com/55874862/184097742-d7221a9c-e1f1-4564-92e5-11b1ec1eb025.png)

also can be seen in downloaded data files
Live
![image](https://user-images.githubusercontent.com/55874862/184097096-e1ca3dea-c12a-4a37-b4c6-e01b72f6bae4.png)

Dev
![image](https://user-images.githubusercontent.com/55874862/184097283-def5fee8-5487-4ed0-ba2b-be973052ccf6.png)

_Originally posted by @liamie in https://github.com/CSOIreland/PxStat/issues/610#issuecomment-1211705623_

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
This I think is still occurring in build update.

Maybe related: Build>create>import does not seem to recognise copyrights where as Build>update>import seems to recognise on the same files

**Comment by neilfromcork** [comment]
Copyright should be ok now. Build update returns double dots for empty values. @liamie

**Comment by liamie** [comment]
Copyright now correct.

However Build Update still not creating the px file for new periods
![image](https://user-images.githubusercontent.com/55874862/184338062-85e32c62-cee9-43d0-b68e-1f8ba673ae73.png)

also in the Download CSV
The label/units true/false button does has no effect on the csv produced in dev it is always without labels and unit
![image](https://user-images.githubusercontent.com/55874862/184338387-10ef57eb-f998-411d-b6d1-e437cc98d512.png)

**Comment by neilfromcork** [comment]
Labels issue fixed. 
Issue of spurious warning re no valid records fixed

**Comment by liamie** [comment]
Produces a px file now
However Elimination Variables missing
Notes Missing
Precision Missing


Also head/stub order different so the data shape profile block is also altered (may not be issue for this but can it be the same for easier comparison?)

**Comment by neilfromcork** [comment]
NOTES stored with inverted commas @damiancosmoschapman 
Elimination ok now
PRECISION- Subkey value not being picked up by parser @damiancosmoschapman 
Stub/heading - business decision but this will depend on dimension order since 5.0.0 @liamie

**Comment by liamie** [comment]
Precision handled different between live and dev in bulid update 

in live note the case on statistic and the decimals of the data is maintained in the output
![image](https://user-images.githubusercontent.com/55874862/191499893-8aa39d55-b4b1-47c8-874a-76b762c715ee.png)

in dev the case on statistic different? and the precision is applied to the file rather than visual so data has been changed?
![image](https://user-images.githubusercontent.com/55874862/191500508-5e7d3054-c18d-4bd7-84a1-7c86cc43504a.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by neilfromcork** [comment]
Decimal places not being applied to values in px output

**Comment by neilfromcork** [comment]
Fixed in DEV values should line up with precisions- ready for test

**Comment by liamie** [comment]
This seems correct now
